#server:
#  port: 8081
#spring:
#  profiles:
#    active: prod
#---
#server:
#  port: 8082
#spring:
#  profiles:dev
#---
#server:
#  port: 8083
#spring:
#  profiles:prod
#---
#对象写法
#行内写法  friends: {lastName: zhangsan, age: 18}
#行外写法  friends:
#             lastName: zhangsan
#             age: 20

#数组（List,Set）
#pets:
# - cat
# - dog
# - pig
#行内写法
#pets: [cat, dog, pig]

person:
  lastName: 张三${random.uuid}
  age: ${random.int}
  boss: false
  birth: 2017/12/12
  map: {k1: v1, k2: 12}
  list:
  - lisi
  - zhaoliu
  dog:
    name: ${person.hello:123}_dog
    age: 2